/* Configuration for list_crates generated by Alire */
#ifndef LIST_CRATES_CONFIG_H
#define LIST_CRATES_CONFIG_H

#define CRATE_VERSION "0.1.0-dev"
#define CRATE_NAME "list_crates"

#define ALIRE_HOST_OS "macos"

#define ALIRE_HOST_ARCH "x86_64"

#define ALIRE_HOST_DISTRO "macports"

#define BUILD_PROFILE_RELEASE 1
#define BUILD_PROFILE_VALIDATION 2
#define BUILD_PROFILE_DEVELOPMENT 3

#define BUILD_PROFILE  3

#define TRACE_LEVEL_INFO 1
#define TRACE_LEVEL_DETAILS 2
#define TRACE_LEVEL_DEBUG 3

#define TRACE_LEVEL  1

#endif
